### ISSUE TITLE
PHP Warning: Undefined array key "PageTypes."

### ISSUE THREAD

**Issue by format-gmbh** [punktDe/quickedit#15]
PHP Warning: Undefined array key "PageTypes." in typo3conf/ext/quickedit/Classes/Backend/PageLayoutHeader.php line 203

where does the error occur:
Backend Modul "Page"  -> choose any page

quickedit 1.0.0
TYPO3 11.5.16
PHP 8.1
composer mode

**Comment by alex-boehm** [comment]
@format-gmbh New version of this extension is now available :)

Thanks again fpr this bug report.

**Comment by format-gmbh** [comment]
Thank you very much.
