### ISSUE TITLE
Add support for TYPO3 11 LTS

### ISSUE THREAD

**Issue by alex-boehm** [punktDe/quickedit#6]
For TYPO3 11 LTS is available now the extension needs to be updated and tested.

**Comment by revoltek-daniel** [comment]
Would like to see an update. 

I've tried to update the code, but i'm not the frontend guy and most of the issues seem to be with bootstrap 5. 
I've created a fork which seems to work fine.
https://github.com/punktDe/quickedit/compare/master...revoltek-daniel:quickedit:feature/update-for-typo3v11

**Comment by alex-boehm** [comment]
Hi @revoltek-daniel,

thank you very much for feedback and for your code changes.
I will take a look on your forke as soon as possible and integrate your changes into our current development for this extension.

Hopefully we will see a TYPO3 11 compatible version very soon :)

**Comment by alex-boehm** [comment]
Hi @revoltek-daniel,

a TYPO3 11 compatible version of this extension is available now :)
Thanks again for your changes, I used some of them in our update branch.

Feel free to test the new version and give us feedback if you find a problem.
